// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "iruyan-api/models"

	mock "github.com/stretchr/testify/mock"

	responses "iruyan-api/responses"

	time "time"

	uuid "github.com/google/uuid"
)

// RoomUsecase is an autogenerated mock type for the RoomUsecase type
type RoomUsecase struct {
	mock.Mock
}

// CreateRoom provides a mock function with given fields: roomName
func (_m *RoomUsecase) CreateRoom(roomName string) (*models.Room, error) {
	ret := _m.Called(roomName)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 *models.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Room, error)); ok {
		return rf(roomName)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Room); ok {
		r0 = rf(roomName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(roomName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateRoomWithSeats provides a mock function with given fields: name, seatCount
func (_m *RoomUsecase) CreateRoomWithSeats(name string, seatCount int) error {
	ret := _m.Called(name, seatCount)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoomWithSeats")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = rf(name, seatCount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnterRoom provides a mock function with given fields: iruyanID, roomID, task
func (_m *RoomUsecase) EnterRoom(iruyanID string, roomID uuid.UUID, task string) (*models.WorkTime, *models.Room, error) {
	ret := _m.Called(iruyanID, roomID, task)

	if len(ret) == 0 {
		panic("no return value specified for EnterRoom")
	}

	var r0 *models.WorkTime
	var r1 *models.Room
	var r2 error
	if rf, ok := ret.Get(0).(func(string, uuid.UUID, string) (*models.WorkTime, *models.Room, error)); ok {
		return rf(iruyanID, roomID, task)
	}
	if rf, ok := ret.Get(0).(func(string, uuid.UUID, string) *models.WorkTime); ok {
		r0 = rf(iruyanID, roomID, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WorkTime)
		}
	}

	if rf, ok := ret.Get(1).(func(string, uuid.UUID, string) *models.Room); ok {
		r1 = rf(iruyanID, roomID, task)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.Room)
		}
	}

	if rf, ok := ret.Get(2).(func(string, uuid.UUID, string) error); ok {
		r2 = rf(iruyanID, roomID, task)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetRoomByID provides a mock function with given fields: roomID
func (_m *RoomUsecase) GetRoomByID(roomID uuid.UUID) (*models.Room, error) {
	ret := _m.Called(roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoomByID")
	}

	var r0 *models.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*models.Room, error)); ok {
		return rf(roomID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *models.Room); ok {
		r0 = rf(roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRooms provides a mock function with no fields
func (_m *RoomUsecase) GetRooms() ([]responses.RoomDetail, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRooms")
	}

	var r0 []responses.RoomDetail
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]responses.RoomDetail, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []responses.RoomDetail); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]responses.RoomDetail)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSeatedUsers provides a mock function with given fields: roomID
func (_m *RoomUsecase) GetSeatedUsers(roomID uuid.UUID) ([]responses.SeatStatusResponse, error) {
	ret := _m.Called(roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetSeatedUsers")
	}

	var r0 []responses.SeatStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]responses.SeatStatusResponse, error)); ok {
		return rf(roomID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []responses.SeatStatusResponse); ok {
		r0 = rf(roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]responses.SeatStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LeaveRoom provides a mock function with given fields: iruyanID, roomID, duration
func (_m *RoomUsecase) LeaveRoom(iruyanID string, roomID uuid.UUID, duration time.Duration) (*responses.LeaveRoomResponse, error) {
	ret := _m.Called(iruyanID, roomID, duration)

	if len(ret) == 0 {
		panic("no return value specified for LeaveRoom")
	}

	var r0 *responses.LeaveRoomResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, uuid.UUID, time.Duration) (*responses.LeaveRoomResponse, error)); ok {
		return rf(iruyanID, roomID, duration)
	}
	if rf, ok := ret.Get(0).(func(string, uuid.UUID, time.Duration) *responses.LeaveRoomResponse); ok {
		r0 = rf(iruyanID, roomID, duration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*responses.LeaveRoomResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, uuid.UUID, time.Duration) error); ok {
		r1 = rf(iruyanID, roomID, duration)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LeaveSeat provides a mock function with given fields: iruyanID, roomID, seatNumber
func (_m *RoomUsecase) LeaveSeat(iruyanID string, roomID uuid.UUID, seatNumber int) error {
	ret := _m.Called(iruyanID, roomID, seatNumber)

	if len(ret) == 0 {
		panic("no return value specified for LeaveSeat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, uuid.UUID, int) error); ok {
		r0 = rf(iruyanID, roomID, seatNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TakeSeat provides a mock function with given fields: iruyanID, roomID, seatNumber
func (_m *RoomUsecase) TakeSeat(iruyanID string, roomID uuid.UUID, seatNumber int) error {
	ret := _m.Called(iruyanID, roomID, seatNumber)

	if len(ret) == 0 {
		panic("no return value specified for TakeSeat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, uuid.UUID, int) error); ok {
		r0 = rf(iruyanID, roomID, seatNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRoomUsecase creates a new instance of RoomUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoomUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoomUsecase {
	mock := &RoomUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
