services:
  frontend:
    container_name: iruyan-front
    build: ./iruyan-front
    ports:
      - "3000:3000"
    volumes:
      - ./iruyan-front:/app
      - /app/node_modules  # ホストのnode_modulesをマウントから除外
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend
      - db
    command: yarn dev

  backend:
    container_name: iruyan-api
    build: ./iruyan-api
    ports:
      - "8080:8080"
    volumes:
      - ./iruyan-api:/app  # ホストのソースコードをコンテナ内にマウントしてホットリロード対応
    environment:
      - GO_ENV=development
      - DATABASE_URL=postgres://user:password@db:5432/exampledb
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: exampledb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
