version: "3"

includes:
  backend: ./iruyan-api/Taskfile.yml

tasks:
  default:
    desc: "タスク一覧を表示する"
    cmds:
      - task --list

  build:
    desc: "Dockerコンテナをビルドする"
    cmds:
      - docker compose --build

  run:
    desc: "Dockerコンテナを起動する"
    cmds:
      - docker-compose up -d

  run-api:
    desc: "バックエンド と DB を起動"
    cmds:
      - docker compose up -d db
      - docker compose up -d backend

  down:
    desc: "Dockerコンテナを停止する"
    cmds:
      - docker-compose down

  clean:
    desc: "Dockerのボリュームを削除する"
    cmds:
      - docker-compose down -v
