// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "iruyan-api/models"

	mock "github.com/stretchr/testify/mock"

	responses "iruyan-api/responses"

	uuid "github.com/google/uuid"
)

// WorkTimeUsecase is an autogenerated mock type for the WorkTimeUsecase type
type WorkTimeUsecase struct {
	mock.Mock
}

// EnterRoom provides a mock function with given fields: iruyanID, roomID, task
func (_m *WorkTimeUsecase) EnterRoom(iruyanID string, roomID uuid.UUID, task string) (*models.WorkTime, error) {
	ret := _m.Called(iruyanID, roomID, task)

	if len(ret) == 0 {
		panic("no return value specified for EnterRoom")
	}

	var r0 *models.WorkTime
	var r1 error
	if rf, ok := ret.Get(0).(func(string, uuid.UUID, string) (*models.WorkTime, error)); ok {
		return rf(iruyanID, roomID, task)
	}
	if rf, ok := ret.Get(0).(func(string, uuid.UUID, string) *models.WorkTime); ok {
		r0 = rf(iruyanID, roomID, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WorkTime)
		}
	}

	if rf, ok := ret.Get(1).(func(string, uuid.UUID, string) error); ok {
		r1 = rf(iruyanID, roomID, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllWorkTimes provides a mock function with no fields
func (_m *WorkTimeUsecase) GetAllWorkTimes() ([]models.WorkTime, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllWorkTimes")
	}

	var r0 []models.WorkTime
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.WorkTime, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.WorkTime); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WorkTime)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLatestEntry provides a mock function with given fields: iruyanID, roomID
func (_m *WorkTimeUsecase) GetLatestEntry(iruyanID string, roomID uuid.UUID) (*models.WorkTime, error) {
	ret := _m.Called(iruyanID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestEntry")
	}

	var r0 *models.WorkTime
	var r1 error
	if rf, ok := ret.Get(0).(func(string, uuid.UUID) (*models.WorkTime, error)); ok {
		return rf(iruyanID, roomID)
	}
	if rf, ok := ret.Get(0).(func(string, uuid.UUID) *models.WorkTime); ok {
		r0 = rf(iruyanID, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.WorkTime)
		}
	}

	if rf, ok := ret.Get(1).(func(string, uuid.UUID) error); ok {
		r1 = rf(iruyanID, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecentLogs provides a mock function with given fields: iruyanID, limit
func (_m *WorkTimeUsecase) GetRecentLogs(iruyanID string, limit int) ([]responses.WorkTimeLog, error) {
	ret := _m.Called(iruyanID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentLogs")
	}

	var r0 []responses.WorkTimeLog
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]responses.WorkTimeLog, error)); ok {
		return rf(iruyanID, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int) []responses.WorkTimeLog); ok {
		r0 = rf(iruyanID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]responses.WorkTimeLog)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(iruyanID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWeeklyLogs provides a mock function with given fields: iruyanID
func (_m *WorkTimeUsecase) GetWeeklyLogs(iruyanID string) ([]responses.WorkTimeResponse, error) {
	ret := _m.Called(iruyanID)

	if len(ret) == 0 {
		panic("no return value specified for GetWeeklyLogs")
	}

	var r0 []responses.WorkTimeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]responses.WorkTimeResponse, error)); ok {
		return rf(iruyanID)
	}
	if rf, ok := ret.Get(0).(func(string) []responses.WorkTimeResponse); ok {
		r0 = rf(iruyanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]responses.WorkTimeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(iruyanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkLogForLastWeek provides a mock function with given fields: iruyanID
func (_m *WorkTimeUsecase) GetWorkLogForLastWeek(iruyanID string) (responses.WorkLogForLastWeekResponse, error) {
	ret := _m.Called(iruyanID)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkLogForLastWeek")
	}

	var r0 responses.WorkLogForLastWeekResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (responses.WorkLogForLastWeekResponse, error)); ok {
		return rf(iruyanID)
	}
	if rf, ok := ret.Get(0).(func(string) responses.WorkLogForLastWeekResponse); ok {
		r0 = rf(iruyanID)
	} else {
		r0 = ret.Get(0).(responses.WorkLogForLastWeekResponse)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(iruyanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWorkTimeByIruyanID provides a mock function with given fields: iruyanID
func (_m *WorkTimeUsecase) GetWorkTimeByIruyanID(iruyanID string) ([]models.WorkTime, error) {
	ret := _m.Called(iruyanID)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkTimeByIruyanID")
	}

	var r0 []models.WorkTime
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]models.WorkTime, error)); ok {
		return rf(iruyanID)
	}
	if rf, ok := ret.Get(0).(func(string) []models.WorkTime); ok {
		r0 = rf(iruyanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WorkTime)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(iruyanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTask provides a mock function with given fields: iruyanID, task
func (_m *WorkTimeUsecase) UpdateTask(iruyanID string, task string) error {
	ret := _m.Called(iruyanID, task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(iruyanID, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWorkTimeUsecase creates a new instance of WorkTimeUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWorkTimeUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *WorkTimeUsecase {
	mock := &WorkTimeUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
