version: 2

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive

linters-settings:
  revive:
    confidence: 0.8
    severity: warning
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/OverAgers/iruyan

run:
  timeout: 5m
