version: "3"

tasks:
  default:
    desc: "タスク一覧を表示"
    cmds:
      - task --list

  setup:
    desc: "aqua によるツールインストール"
    silent: true
    cmds:
      - echo "📦 aqua による CLI ツールのインストールを開始..."
      - aqua i
      - echo "✅ ツールのインストールが完了しました"

  swag:
    desc: "Docker内のbackendでSwaggerドキュメントを生成"
    cmds:
      - docker compose exec backend /bin/sh -c "/go/bin/swag init -g main.go -o ./docs"
