// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "iruyan-api/models"

	mock "github.com/stretchr/testify/mock"
)

// AuthUsecase is an autogenerated mock type for the AuthUsecase type
type AuthUsecase struct {
	mock.Mock
}

// LoginUser provides a mock function with given fields: iruyanID, password
func (_m *AuthUsecase) LoginUser(iruyanID string, password string) (*models.User, error) {
	ret := _m.Called(iruyanID, password)

	if len(ret) == 0 {
		panic("no return value specified for LoginUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*models.User, error)); ok {
		return rf(iruyanID, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *models.User); ok {
		r0 = rf(iruyanID, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(iruyanID, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogoutUser provides a mock function with given fields: iruyanID
func (_m *AuthUsecase) LogoutUser(iruyanID string) (*models.User, error) {
	ret := _m.Called(iruyanID)

	if len(ret) == 0 {
		panic("no return value specified for LogoutUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.User, error)); ok {
		return rf(iruyanID)
	}
	if rf, ok := ret.Get(0).(func(string) *models.User); ok {
		r0 = rf(iruyanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(iruyanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterUser provides a mock function with given fields: name, iruyanID, password, email
func (_m *AuthUsecase) RegisterUser(name string, iruyanID string, password string, email string) (*models.User, error) {
	ret := _m.Called(name, iruyanID, password, email)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) (*models.User, error)); ok {
		return rf(name, iruyanID, password, email)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string) *models.User); ok {
		r0 = rf(name, iruyanID, password, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string) error); ok {
		r1 = rf(name, iruyanID, password, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthUsecase creates a new instance of AuthUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUsecase {
	mock := &AuthUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
