name: Go CI

on:
  push:
    branches: ["staging"]
  pull_request:
    branches: ["staging"]

env:
  WORKING_DIRECTORY: ./iruyan-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.WORKING_DIRECTORY }}/go.mod
          cache: true

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.64.8
          working-directory: ${{ env.WORKING_DIRECTORY }}
          args: --config=.golangci.v1.yml --timeout=5m

      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: go build -v ./...

      - name: Test
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: go test -v ./...
